jobs:
  build:
    runs-on: ubuntu-latest
    # Define a pasta correta para todo o processo ⤵️
    defaults:
      run:
        working-directory: ./nome-da-sua-subpasta 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: '20'

      - name: Install dependencies
        run: npm ci # ou npm install

      - name: Build project
        run: npm run build
